# Generated by Django 2.2.14 on 2021-06-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book_Inventory_APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='created_date',
        ),
    ]
